[window]
opacity = 0.8

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 14.0

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
    #"~/.config/alacritty/themes/themes/autumn.toml"
    #"~/.config/alacritty/themes/themes/rose_pine.toml"
]

